[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx tsx server-prod.ts"
healthcheckPath = "/api/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
